exports.hunts = ->
	[
		"terwijl je tanden poets"
		"terwijl je fietst"
		"terwijl je iemand kust"
		"met een pet op"
		"met een politie-agent"
		"terwijl je bier drinkt"
		"met een paspop"
		"op een schommel"
		"terwijl je iemand optilt"
		"met iemand met hetzelfde shirt"
		"in de lift"
		"terwijl je ijs eet"
		"knuffelend met een knuffeldier"
		"met een zonnebril met gele glazen op"
		"met een skibril op"
		"terwijl je een sigaar rookt"
		"met één van je ouders"
		"met slagroom op je gezicht"
		"terwijl je een kauwgom-bel blaast"
		"liggend op straat"
		"met een medaille om je nek"
		"terwijl je een huisdier aait"
		"in een winkelwagentje"
		"met shampoo in je haar"
		"onder een niet-parkeer bord"
		"met een bloem in je haar"
		"op een glijbaan"
		"onder een paraplu"
		"knuffelend met een boom"
		"in een kerk"
		"met een Ford Ka"
		"met 3 kussens op je hoofd gebalanceerd"
		"terwijl je push-ups doet"
		"met een (echte!) baby in je handen"
		"terwijl je verft"
		"op een loopband"
		"gereflecteerd in water"
		"met een gitaar"
		"terwijl je spruitjes eet"
		"terwijl je speelt met lego"
		"met een vinyl LP"
		"terwijl je een ballon opblaast"
		"pratend tegen een rubber eend"
		"hangend in de lucht"
		"met negen anderen"
		"in de bibliotheek"
		"op het dak"
		"helemaal in het wit gekleed"
		"in je pyjama"
		"in een trein"
		"met de krant van vandaag"
		"op een skateboard"
		"met gras in je mond"
		"in klaslokaal"
		"zwaaiend met een (grote) vlag"
		"met een theelepel hangend aan je neus"
		"terwijl je een frisbee gooit"
		"met een panty over je hoofd"
		"hangend onder een tafel"
		"terwijl je een brief post"
		"in de bioscoop"
		"terwijl je pannenkoeken bakt"
		"terwijl je het vuilnis buiten zet"
		"ingerold in een gordijn"
		"terwijl je door een rietje drinkt"
		"terwijl je een kaars aansteekt"
		"liggend in het gras"
		"schreeuwend"
		"met oorwarmers op"
		"terwijl je dartpijl gooit"
		"in een draaideur"
		"terwijl je je scheert"
		"oneindig gereflecteerd in 2 spiegels"
		"met een Rubik's Cube"
		"met een foto van jezelf"
		"op een brug"
		"in bed"
		"met een roze shirt aan"
		"in de kroeg"
		"in sportkleding"
		"terwijl je een paard aait"
		"met een bril op"
		"in de achterbak van een auto"
		"terwijl je piano speelt"
		"met een vlinderdas (strikje) om"
		"met een origami zwaan"
		"terwijl je in een straatlantaarn klimt"
		"terwijl je een banaan eet"
		"met een onesie aan"
		"met een supermarkt caissière"
		"met een cassette walkman"
		"met superman kleding aan"
		"met je middelbare school diploma"
		"met een fluitende fluitketel"
		"op skates"
		"met moonboots aan"
		"met een gemonteerde vlieger"
		"met een briefje van 100"
		"druipend van het zweet"
		"voor een egaal rode achtergrond"
		"terwijl je popcorn eet"
		"in zeiknatte kleren"
		"terwijl je in bad zit"
		"met een helm op"
		"terwijl je geld geeft aan een straatartiest"
		"in een tent"
		"met een stoplicht"
		"liggend in een hangmat"
		"met je mond dichtgetaped"
		"met een tuinkabouter"
		"terwijl je spaghetti slurpt"
		"voor een museum"
		"met een groentekraampje"
		"terwijl je over een hek klimt"
		"met teveel lipstick op"
		"bij een bushalte"
		"in het midden van een rotonde"
		"met een pruik op"
		"met een standbeeld"
		"met een clownsneus op"
		"met al je kleren binnenstebuiten aan"
		"met twee horloges om"
		"met een Playboy tijdschrift"
		"in een McDonald's"
		"terwijl je met je tong je neus probeert aan te raken"
		"terwijl je iemands oor likt"
		"terwijl je iemands schoenen kust"
		"met een vol glas balancerend op je hoofd"
		"met een bowling ball"
		"zwemmend"
		"gekleed in kostuum of avondjurk"
		"in een garage"
		"zittend op de wc"
		"met een lampenkap op je hoofd"
		"terwijl je Harry Potter leest"
		"in een handstand"
		"met een analoge telefoon"
		"terwijl je een halter optilt"
		"met je naam op je voorhoofd geschreven"
		"in een auto wasstraat"
		"gewikkeld in wc-papier"
		"terwijl je eet met stokjes"
		"terwijl je een zoute haring eet"
		"met een Hawai shirt aan"
		"ondersteboven"
		"terwijl je in je grote teen probeert te bijten"
		"gezien door een vergrootglas"
		"met iemand anders die ook een selfie maakt"
		"'vliegend' op een bezem"
		"met een hoedje van aluminium folie"
		"scheelkijkend"
		"met iemand die ouder is dan 70"
		"met klompen aan"
		"met een kinderwagen"
		"met een bus- of taxi-chauffeur"
		"met een poncho aan"
		"met een insect op je vingertop"
		"met een handdoek omgeslagen als cape"
		"terwijl je een moddermasker op hebt"
		"zonnebadend op een handdoek"
		"'planking'"
		"terwijl je een tomaat fijnknijpt"
		"met een CD/DVD balancerend op je neus"
		"met een blauwe tong"
		"met een stopdas, Rambo-stijl"
		"terwijl je de Bijbel leest"
		"terwijl je trost een bokaal vasthoudt"
		"met een bal balancerend op je vinger"
		"stofzuigend"
		"met snoephartjes op je ogen"
		"met een kroontje of tiara op"
		"terwijl je passievol een barkruk knuffelt"
		"voor een filmposter"
		"met een game console controller in je hand"
		"op een zitzak"
		"bij een concert"
		"terwijl je een cocktail drinkt"
		"breiend"
		"met een kokmuts op"
		"touwtje-trekkend met een hond"
		"met een badmuts op"
		"terwijl je je haar föhnt"
		"met een tandpasta-snor"
		"met een goudvis"
		"met een handdoek als tulband op je hoofd"
		"terwijl je een draad door een naald doet"
		"achter tralies"
		"met een postzegel op je voorhoofd"
		"met een vuilniswagen"
		"liggend op een bankje in het park"
		"met een slag in je handen"
		"terwijl je je eigen naam Googlet"
		"in een lingerie-winkel"
		"met 4 post-its op je gezicht"
		"pronkend met je biceps"
		"met je hoofd onder water"
		"met een badminton shuttle"
		"met 5 truien aan"
		"terwijl je de planten water geeft"
		"terwijl je je schoenen poets"
		"terwijl je kleren strijkt"
		"met een sombrero op"
		"pronkend met een CD uit de jaren '90"
		"met 5 telefoons in je handen"
		"onder een paraplu met 2 anderen"
		"met ogen getekend op je oogleden"
		"met een hanekam kapsel"
		"terwijl 2 balpennen uit je neus steken"
		"met knijpers op beide oren"
		"met een 4-hoog kaartenhuis"
		"met een wereldbol"
		"met een balpen geballanceerd op je voorhoofd"
		"terwijl je een hond imiteren"
		"met een koe"
		"door de ruit hangend"
		"in een cafe"
		"in een frituur"
		"met één van je grootouders"
		"in een kast"
		"met 5 boeken op je hoofd"
		"met een persoon die Matthias heet"
		"onder je bed"
		"terwijl je een appel eet"
		"met een varken"
		"met 2 vingers in je neus"
		"met een computermuis"
		"met 2 katten en/of honden"
		"met een bekend persoon"
		"met pate"
		"zonder broek"
		"met een kauwgum in je neus geplakt"
		"met slagroom op je buik"
	]
