exports.hunts = ->
	[
		"Lavándote los dientes"
		"Montando en bici"
		"Besando a alguien"
		"Llevando una gorra"
		"Y un oficial de policía"
		"Bebiendo una jarra de cerveza"
		"Con un maniquí en una tienda"
		"Sentado en un columpio"
		"Llevando a alguien"
		"Con alguien llevando la misma camiseta"
		"En un ascensor"
		"Comiendo un helado"
		"Abrazando a un peluche"
		"Llevando gafas de sol amarillas"
		"Llevando gafas de eski"
		"Fumando un cigarrillo"
		"Y uno de tus padres"
		"Con nata en la cara"
		"Haciendo pompas de chicle"
		"Tirado en la calle"
		"Llevando una medalla"
		"Acariciando a un animal"
		"En un carrito de la compra"
		"Lavándote el pelo"
		"Debajo de una señal de aparcamiento"
		"Con una flor en el pelo"
		"En un tobogán"
		"Debajo de un paraguas"
		"Abrazando a un árbol"
		"En una iglesia"
		"Con un Ford Ka"
		"Haciendo equilibrio con 3 cojines en la cabeza"
		"Haciendo flexiones"
		"Sujetando a un bebé (¡real!)"
		"Pintando"
		"En una cinta de correr"
		"Reflejado en el agua"
		"Con una guitarra"
		"Comiendo germinados"
		"Jugando con lego"
		"Sujetando un vinilo"
		"Inflando un globo"
		"Hablando con un pato de goma"
		"En el aire"
		"Con otras nueve personas"
		"En una biblioteca"
		"De pie en un tejado"
		"Vestido todo blanco"
		"En pijama"
		"En un tren"
		"Con el periódico de hoy"
		"En un monopatín"
		"Con hierba en la boca"
		"En una clase"
		"Agitando una bandera (de tamaño real)"
		"Con una cuchara colgada de la nariz"
		"Lanzando un frisbee"
		"Con una media en la cabeza"
		"Colgado debajo de la mesa"
		"Enviando una carta"
		"En un cine"
		"Haciendo tortitas"
		"Sacando la basura"
		"Envuelto en las cortinas"
		"Bebiendo con una pajita"
		"Encendiendo una vela"
		"Tumbado en el césped"
		"Gritando"
		"Llevando orejeras"
		"Jugando a los dardos"
		"En una puerta giratoria"
		"Afeitándote"
		"Reflejado infinitamente en dos espejos"
		"Sujetando un cubo de Rubik"
		"Sujetando una foto de ti mismo"
		"En un puente"
		"Acostado en la cama"
		"Llevando una camiseta rosa"
		"En un bar"
		"Con ropa de deporte"
		"Acariciando un caballo"
		"Llevando gafas"
		"En el maletero de un coche"
		"Tocando el piano"
		"Llevando una pajarita"
		"Sujetando un cisne de papiroflexia"
		"Subiendo a una farola"
		"Comiendo un plátano"
		"Llevando un mono"
		"Con una cajera de supermercado"
		"Sujetando un walkman"
		"Llevando un producto de Superman"
		"Mostrando tu diploma del instituto"
		"Con una tetera humeante"
		"Llevando patines de hielo"
		"En la calle con botas de nieve"
		"Sujetando una cometa"
		"Sujetando un billete de 100$ o 100€"
		"Sudando bastante"
		"Solo con un fondo rojo"
		"Comiendo palomitas"
		"Con la ropa empapada"
		"Tomando un baño"
		"Llevando un caco"
		"Dando dinero a un artista callejero"
		"En una tienda de campaña"
		"Con un semáforo"
		"Tumbado en una hamaca"
		"Con la boca cerrada con cinta de celo"
		"Con un enano de jardín"
		"Sorbiendo espaguetis"
		"Delante de un museo"
		"Con un puesto de verduras"
		"Escalando una valla"
		"Llevando demasiado pintalabios"
		"En una parada de autobús"
		"En el centro de una rotonda"
		"Llevando una peluca"
		"Con una estatua"
		"Llevando una nariz de payaso"
		"Llevando la ropa del revés"
		"Llevando dos relojes"
		"Leyendo una revista de Playboy"
		"En un McDonal's"
		"Intentando que la lengua te toque la nariz"
		"Lamiéndole la oreja a alguien"
		"Besando las botas de alguien"
		"Haciendo equilibrio con un vaso lleno en la cabeza"
		"Sujetando una bola de bolos"
		"Nadando"
		"Levando un traje o un vestido de noche"
		"Hablando con un títere"
		"En un cubo de la basura"
		"Sentado en el retrete"
		"Con una lámpara encima de la cabeza"
		"Leyendo Harry Potter"
		"Haciendo el pino"
		"Con un teléfono analógico"
		"Levantando una pesa"
		"Con tu nombre escrito en la frente"
		"En un tren de lavado de coches"
		"Envuelto en papel higiénico"
		"Comiendo con palillos"
		"Comiendo un arenque en escabeche"
		"Llevando una camisa hawaiana"
		"Del revés"
		"Intentando morderte el dedo gordo del pie"
		"A través de una lupa"
		"Con otra persona haciéndose un selfie"
		"Montado en una escoba"
		"Llevando un sombrero de papel de aluminio"
		"Cruzando los ojos"
		"Con alguien de más de 70 años"
		"Llevando zapatos de madera"
		"Llevando un cochecito de bebé"
		"Con un conductor de autobús/taxista"
		"Llevando un poncho"
		"Con un insecto en la punta del dedo"
		"Llevando una toalla como si fuera una capa"
		"Con una mascarilla de barro"
		"Tomando en sol en una toalla"
		"Haciendo planking"
		"Aplastando un tomate con las manos"
		"Haciendo equilibrios con un CD/DVD en la nariz"
		"Enseñando la lengua azul"
		"Llevando una corbata al estilo de Rambo"
		"Leyendo una biblia"
		"Mostrando un trofeo"
		"Haciendo equilibrios con una pelota en el dedo"
		"Pasando la aspiradora"
		"Con corazones (de chuchería) en los ojos"
		"Haciendo sombras chinas con las manos"
		"Llevando una corona o una tiara"
		"Abrazando apasionadamente un taburete de bar"
		"Delante de un póster de película"
		"Sosteniendo un mando de una consola"
		"En un puff"
		"En un concierto"
		"Bebiendo un cóctel"
		"Tejiendo"
		"Llevando un sombrero de cocinero"
		"Jugando al tira y afloja con un perro"
		"Llevando un gorro de ducha"
		"Secándote el pelo con un secador"
		"Con un bigote hecho de pasta de dientes" # nuevo desde aquí"
		"Con un pez de colores"
		"Llevando una toalla en la cabeza"
		"Enhebrando una aguja"
		"Detrás de las rejas"
		"Con un sello en la frente"
		"Con un camión de la basura"
		"Acostado en un banco de un parque"
		"Sujetando un caracol"
		"Buscando en Google tu propio nombre"
		"En una tienda de lencería"
		"Con 4 post-its en la cara"
		"Sacando bíceps"
		"Con la cara sumergida en agua"
		"Sujetando un volante de bádminton"
		"Llevando 5 jerséis"
		"Regando las plantas"
		"Sacando brillo a los zapatos"
		"Planchando la ropa"
		"Llevando un sombrero"
		"Mostrando con orgullo un CD de los 90"
		"Sosteniendo 5 teléfonos móviles"
		"Debajo de un paraguas con otras 2 personas"
		"Con ojos dibujados en los párpados"
		"Con una cresta"
		"Con lápices saliendo de la nariz"
		"Con pinzas de la ropa en las orejas"
		"Con un castillo de cartas de 4 pisos"

	]