exports.hunts = ->
	[
		"Vous brossant les dents"
		"Faisant du vélo"
		"Embrassant quelqu'un"
		"Avec une casquette"
		"Avec un policier"
		"Buvant une bière"
		"Avec un mannequin de boutique"
		"Assis sur une balançoire"
		"Portant quelqu'un"
		"Avec quelqu'un qui porte la même chemise"
		"Dans un ascenseur"
		"Mangeant une crème glacée"
		"Faisant un câlin à une peluche"
		"Portant des lunettes de soleil jaunes"
		"Portant des lunettes de ski"
		"Fumant un cigare"
		"Avec un de vos parents"
		"Avec de la crème fouettée sur le visage"
		"Faisant une bulle de chewing-gum"
		"Allongé dans la rue"
		"Portant une médaille"
		"Caressant un animal"
		"Dans un chariot de supermarché"
		"Lavant vos cheveux"
		"Sous un panneau de stationnement"
		"Avec une fleur dans les cheveux"
		"Sur une balançoire"
		"Sous un parapluie"
		"Serrant un arbre dans vos bras"
		"Dans une église"
		"Avec une Ford Ka"
		"Maintenant 3 oreillers en équilibre sur votre tête"
		"Faisant des pompes"
		"Portant un (vrai !) bébé"
		"Peignant"
		"Sur un tapis de course"
		"Reflété dans l'eau"
		"Avec une guitare"
		"Mangeant des choux"
		"Jouant avec des lego"
		"Tenant un disque vinyle"
		"Gonflant un ballon"
		"Parlant à un canard en plastique"
		"Dans les airs"
		"Avec neuf autres personnes"
		"Dans une bibliothèque"
		"Debout sur un toit"
		"Habillé tout en blanc"
		"En pyjama"
		"Dans le train"
		"Avec le journal d'aujourd'hui"
		"Sur une planche à roulettes"
		"Avec de l'herbe dans la bouche"
		"Dans une salle de classe"
		"Agitant un drapeau (format normal)"
		"Tenant une cuillère avec le nez"
		"Lançant un frisbee"
		"Avec un bas collant sur la tête"
		"Suspendu sous une table"
		"Postant une lettre"
		"Dans un cinéma"
		"Faisant des crêpes"
		"Sortant la poubelle"
		"Enveloppé dans des rideaux"
		"Buvant à la paille"
		"Allumant une bougie"
		"Allongé dans l'herbe"
		"Hurlant"
		"Portant des cache-oreilles"
		"Jouant aux fléchettes"
		"Dans une porte à tambour"
		"Vous rasant"
		"Reflété à l'infini dans deux miroirs"
		"Tenant un Rubik's Cube"
		"Tenant une photo de vous"
		"Sur un pont"
		"Allongé sur un lit"
		"Portant une chemise rose"
		"Dans un café"
		"En tenue de sport"
		"Caressant un cheval"
		"Portant des lunettes"
		"Dans le coffre d'une voiture"
		"Jouant du piano"
		"Portant un nœud papillon"
		"Tenant un cygne en papier plié"
		"Escaladant un lampadaire"
		"Mangeant une banane"
		"Portant une combinaison-pantalon"
		"Avec la caissière de supermarché"
		"Tenant un baladeur à cassettes"
		"Portant des produits Superman"
		"Montrant votre diplôme d'études secondaires"
		"Avec une bouilloire fumante"
		"Portant des patins à glace"
		"Portant des après-skis à l'extérieur"
		"Tenant un cerf-volant monté"
		"Tenant un billet de 100 $ ou de 100 €"
		"Transpirant manifestement"
		"Avec juste un fond rouge clair"
		"Mangeant du popcorn"
		"Dans des vêtements trempés"
		"Prenant un bain"
		"Portant un casque"
		"Donnant une pièce à un artiste de rue"
		"Dans une tente"
		"Avec un feu de circulation"
		"Allongé dans un hamac"
		"Avec du ruban adhésif sur la bouche"
		"Avec un nain de jardin"
		"Mangeant des spaghettis bruyamment"
		"Devant un musée"
		"Avec un étal de légumes"
		"Escaladant une clôture"
		"Portant trop de rouge à lèvres"
		"À un arrêt de bus"
		"Au centre d'un rond-point"
		"Portant une perruque"
		"Avec une statue"
		"Avec un nez de clown"
		"Portant vos vêtements sur l'envers"
		"Portant deux montres"
		"Lisant un magazine Playboy"
		"Dans un McDonalds"
		"Essayant de toucher votre nez avec la langue"
		"Léchant l'oreille de quelqu'un"
		"Embrassant les bottes de quelqu'un"
		"Maintenant un verre plein en équilibre sur votre tête"
		"Tenant une boule de bowling"
		"Nageant"
		"Portant un costume ou une robe de soirée"
		"Parlant à une marionnette en chaussette"
		"Dans une poubelle"
		"Assis sur les toilettes"
		"Avec un abat-jour sur la tête"
		"Lisant Harry Potter"
		"Faisant le poirier"
		"Avec un téléphone analogique"
		"Portant un haltère"
		"Avec votre nom écrit sur le front"
		"Dans un carwash"
		"Enveloppé dans du papier toilette"
		"Mangeant avec des baguettes"
		"Mangeant un hareng mariné"
		"Portant une chemise hawaïenne"
		"À l'envers"
		"Essayant de mordre votre gros orteil"
		"À travers une loupe"
		"Avec quelqu'un d'autre prenant aussi un selfie"
		"Chevauchant un balai"
		"Portant un chapeau en papier d'alu"
		"Louchant"
		"Avec une personne de plus de 70 ans"
		"Portant des sabots"
		"Conduisant une poussette pour bébé"
		"Avec un chauffeur de bus ou de taxi"
		"Portant un poncho"
		"Avec un insecte sur le bout de votre doigt"
		"Portant une serviette comme une cape"
		"Portant un masque de boue"
		"Prenant un bain de soleil sur une serviette"
		"Faisant la planche"
		"Écrasant une tomate dans votre main"
		"Maintenant un CD ou un DVD en équilibre sur votre nez"
		"Montrant une langue bleue"
		"Portant une cravate à la manière de Rambo"
		"Lisant une bible"
		"Exhibant un trophée"
		"Maintenant une balle en équilibre sur votre doigt"
		"Passant l'aspirateur"
		"Avec des cœurs (en bonbons) dans vos yeux"
		"Faisant un lapin en ombre chinoises"
		"Portant une couronne ou un diadème"
		"Étreignant passionnément un tabouret de bar"
		"Devant une affiche de film"
		"Portant une manette de console de jeu"
		"Assis sur un gros pouf"
		"À un concert"
		"Buvant un cocktail"
		"Tricotant"
		"Portant un chapeau de cuisinier"
		"Jouant à tirer une corde avec un chien"
		"Portant un bonnet de douche"
		"Séchant vos cheveux"
		"Avec une moustache de dentifrice" # nouveau à partir d'ici"
		"Avec un poisson rouge"
		"Portant une serviette sur la tête"
		"Enfilant une aiguille"
		"Derrière des barreaux"
		"Avec un timbre-poste sur le front"
		"Avec un camion poubelle"
		"Allongé sur un banc dans un parc"
		"Tenant un escargot"
		"Tapant votre nom sur Google"
		"Dans un magasin de lingerie"
		"Avec 4 post-its sur le visage"
		"Contractant vos biceps"
		"Avec votre visage immergé dans l'eau"
		"Tenant un volant de badminton"
		"Portant 5 pulls"
		"Arrosant des plantes"
		"Cirant des chaussures"
		"Repassant du linge"
		"Portant un sombrero"
		"Montrant fièrement un CD des années 90"
		"Tenant 5 téléphones mobiles"
		"Sous un parapluie avec 2 autres personnes"
		"Avec des yeux dessinés sur vos paupières"
		"Avec une crête dans les cheveux"
		"Avec des crayons sortant de votre nez"
		"Avec des pinces à linge sur vos oreilles"
		"Avec un château de cartes de 4 étages"
		"avec un globe"
		"avec un stylo à bille en équilibre sur votre front"
		"pendant que tu fais un chien"
		"avec une vache"
		"suspendu par la fenêtre"
		"dans un café"
		"dans une friture"
		"avec l'un de vos grands-parents"
		"Dans une armoire"
		"avec 5 livres sur la tête"
		"avec une personne nommée Matthias"
		"sous ton lit"
		"pendant que tu manges une pomme"
		"avec un cochon"
		"avec 2 doigts dans le nez"
		"avec une souris d'ordinateur"
		"avec 2 chats et / ou chiens"
		"avec une personne familière"
		"avec pâté"
		"sans pantalon"
		"avec un chewing-gum dans le nez"
		"avec de la crème fouettée sur le ventre"
	]
