exports.hunts = ->
	[
		"Mentre ti lavi i denti"
		"Vai in bici"
		"Baci qualcuno"
		"Indossi un berretto"
		"E un agente di polizia"
		"Bevendo un bicchiere di birra"
		"Con un manichino di un negozio"
		"Seduto su una altalena"
		"Portando qualcuno"
		"Con qualcuno che indossa la stessa camicia"
		"In un ascensore"
		"Mangiando un gelato"
		"Abbracciando un peluche"
		"Indossando occhiali da sole gialli"
		"Indossando occhiali da sci"
		"Fumando un sigaro"
		"E uno dei tuoi genitori"
		"Con la panna montata sul tuo viso"
		"Soffiando una gomma da masticare"
		"Sdraiato sulla strada"
		"Indossando una medaglia"
		"Coccolando un animale"
		"In un carrello della spesa"
		"Facendo lo shampoo ai capelli"
		"Sotto a un segnale di parcheggio"
		"Indossando un fiore tra i capelli"
		"Su una slitta"
		"Sotto un ombrello"
		"Abbracciando un albero"
		"In una chiesa"
		"Con una Ford Ka"
		"Tenendo in equilibrio 3 cuscini sulla testa"
		"Facendo flessioni"
		"Tenendo in braccio un (vero!) bambino"
		"Dipingendo"
		"Su un tapis roulant"
		"Riflesso nell'acqua"
		"Con una chitarra"
		"Mangiando germogli"
		"Giocando con il lego"
		"Tenendo un disco in vinile"
		"Gonfiando un palloncino"
		"Parlando con una papera di gomma"
		"A mezz'aria"
		"Con altre nove persone"
		"In biblioteca"
		"In piedi su un tetto"
		"Vestito tutto di bianco"
		"In pigiama"
		"Su un treno"
		"Con il giornale di oggi"
		"Su uno skateboard"
		"Con l'erba in bocca"
		"In un'aula"
		"Agitando una bandiera (grande)"
		"Con un cucchiaio appeso al naso"
		"Gettando un frisbee"
		"Con un collant sopra la testa"
		"Appeso sotto un tavolo"
		"Inviando della lettera"
		"In un cinema"
		"Cuocendo frittelle"
		"Portando fuori la spazzatura"
		"Avvolto nelle tende"
		"Bevendo con la cannuccia"
		"Accendendo una candela"
		"Sdraiato nell'erba"
		"Urlando"
		"Indossando cuffie"
		"Giocando a freccette"
		"In una porta girevole"
		"Rasandoti"
		"Con l'infinito riflesso in due specchi"
		"Tenendo il cubo di Rubik"
		"In possesso di una tua foto"
		"Su un ponte"
		"Sdraiata a letto"
		"Indossando una camicia rosa"
		"In un pub"
		"Vestito sportivo"
		"Accarezzando un cavallo"
		"Indossando occhiali"
		"Nel bagagliaio di un'automobile"
		"Suonando il pianoforte"
		"Indossando un papillon"
		"Con in mano un cigno di carta piegata"
		"Arrampicato su un lampione"
		"Mangiando una banana"
		"Indossando una tutina"
		"Con la cassiera del supermercato"
		"Con un walkman a cassette"
		"Indossando prodotti di Superman"
		"Mostrando il tuo diploma di scuola superiore"
		"Con un bollitore da tè fumante"
		"Indossando pattini da ghiaccio"
		"Indossando dopo sci"
		"Con un aquilone assemblato"
		"Tenendo in mano un conto da 100,00 $ o 100,00 €"
		"Sudando in modo evidente"
		"Con solo un semplice sfondo rosso"
		"Mangiando popcorn"
		"Inzuppando i vestiti bagnati"
		"Facendo un bagno"
		"Indossando un casco"
		"Facendo una donazione a un artista di strada"
		"In una tenda"
		"Con un semaforo"
		"In un'amaca"
		"Con la bocca chiusa bendata"
		"Con un nano da giardino"
		"Gustando spaghetti"
		"Davanti a un museo"
		"Con uno stand di verdure"
		"Scavalcando una recinzione"
		"Indossando troppo rossetto"
		"A una fermata dell'autobus"
		"Nel centro di una rotonda"
		"Indossando una parrucca"
		"Con una statua"
		"Indossando un naso da pagliaccio"
		"Indossando i vestiti al rovescio"
		"Indossando due orologi"
		"Leggendo una rivista di Playboy"
		"In un McDonalds"
		"Cercando di toccare il naso con la lingua"
		"Leccando l'orecchio di qualcuno"
		"Baciando li stivali di qualcuno"
		"Tenendo in equilibrio un bicchiere pieno sulla testa"
		"tenendo una palla da bowling"
		"Nuotando"
		"Indossando un completo o un'abito da sera"
		"Parlando con un burattino fatto con un calzino"
		"In un bidone della spazzatura"
		"Seduto sul water"
		"Con un paralume sopra la testa"
		"Leggendo Harry Potter"
		"Facendo una verticale"
		"Con un telefono analogico"
		"Sollevando un manubrio"
		"Con il proprio nome scritto sulla fronte"
		"In un autolavaggio"
		"Avvolto nella cartaigienica"
		"Mangiando con le bacchette"
		"Mangiando una aringa in salamoia"
		"Indossando una camicia hawaiana"
		"Capovolto"
		"Cercando di mordere l'alluce"
		"Attraverso una lente di ingrandimento"
		"Con qualcun altro che sta facendo un selfie"
		"In sella a una scopa"
		"Indossando un cappello di carta stagnola"
		"Incrociando gli occhi"
		"Con qualcuno che ha più di 70 anni"
		"Indossando scarpe di legno"
		"Camminando un passeggino"
		"Con un autista di bus / taxi"
		"Indossando un poncho"
		"Con un insetto sulla punta di un dito"
		"Indossando un asciugamano come mantello"
		"Indossando una maschera di fango"
		"Prendendo il sole su un asciugamano"
		"Facendo lo stupido"
		"Schiacciando un pomodoro con la mano"
		"Tenendo in equilibrio un CD / DVD sul naso"
		"Mostrando una lingua blu"
		"Indossando una cravatta stile Rambo"
		"Leggendo una bibbia"
		"Mettendo in mostra una coppa trofeo"
		"Tenendo in equilibrio una palla sul dito"
		"Pulendo con un'aspirapolvere"
		"Con cuori (caramelle) negli occhi"
		"Facendo l'ombra di un coniglio con le mani"
		"Indossando una corona o un diadema"
		"Abbracciando appassionatamente uno sgabello da bar"
		"Di fronte a un poster di un film"
		"Con un controller della console di un videogioco"
		"Seduto su un sacchetto ciccione"
		"A un concerto"
		"Sorseggiando un cocktail"
		"Lavorando a maglia"
		"Indossando un cappello da cuoco"
		"Giocando al tiro alla corda con un cane"
		"Indossando una cuffia da doccia"
		"Asciugando i capelli con il phon"
		"Con un paio di baffi fatti di dentifricio" # nuovo da qui"
		"Con un pesce rosso"
		"Indossando un asciugamano sulla testa"
		"Infilando un ago"
		"Dietro le sbarre"
		"Con un francobollo sulla fronte"
		"Con un camion della spazzatura"
		"Sdraiato su una panchina"
		"Tenendo una lumaca"
		"Cercando su google il proprio nome"
		"In un negozio di biancheria intima"
		"Con 4 post-it sul viso"
		"Flettendo i bicipiti"
		"Con il viso immerso in acqua"
		"Con una navetta badminton"
		"Indossando 5 maglioni"
		"Innafiando le piante"
		"Lucidando le scarpe"
		"Stirando vestiti"
		"Indossando un sombrero"
		"Mostrando con orgoglio un CD anni '90"
		"Tenendo 5 telefoni cellulari"
		"Sotto un ombrello con altri 2"
		"Con gli occhi disegnati sulle palpebre"
		"Con i capelli stile Mowhawk"
		"Con matite che spuntano dal naso"
		"Con mollette sulle orecchie"
		"Con una casa di carte a 4 piani"
		"con un globo"
		"con una penna a sfera in equilibrio sulla fronte"
		"mentre stai facendo un cane"
		"con una mucca"
		"appeso alla finestra"
		"in un caffè"
		"in una padella"
		"con uno dei tuoi nonni"
		"in un armadio"
		"con 5 libri sulla testa"
		"con una persona di nome Matthias"
		"sotto il tuo letto"
		"mentre mangi una mela"
		"con un maiale"
		"con 2 dita nel naso"
		"con un mouse per computer"
		"con 2 gatti e / o cani"
		"con una persona familiare"
		"con patè"
		"senza pantaloni"
		"con un chewing gum nel naso"
		"con panna montata sulla pancia"
	]
