exports.hunts = ->
	[
		"Deine Zähne putzt"
		"Fahrrad fährst"
		"Jemanden küsst"
		"Eine Kappe trägst"
		"Einen Polizisten neben dir hast"
		"Ein Glas Bier trinkst"
		"Eine Schaufensterpuppe neben dir hast"
		"Auf einer Schaukel sitzt"
		"Jemanden trägst"
		"Mit jemandem zusammen bist, der das gleiche Hemd trägt"
		"In einem Aufzug bist"
		"Eis isst"
		"Ein Stofftier umarmst"
		"Eine gelbe Sonnenbrille trägst"
		"Eine Skibrille trägst"
		"Eine Zigarre rauchst"
		"Mit deinen Eltern zusammen bist"
		"Schlagsahne auf deinem Gesicht hast"
		"Eine Kaugummiblase machst"
		"Auf der Straße liegst"
		"Eine Medaille trägst"
		"Ein Tier streichelst"
		"In einem Einkaufswagen sitzt"
		"Deine Haare einseifst"
		"Unter einem Parkschild stehst"
		"Eine Blume im Haar trägst"
		"Auf einem Schlitten sitzt"
		"Unter einem Regenschirm sitzt"
		"Einen Baum umarmst"
		"In einer Kirche bist"
		"Mit einem Ford Ka posierst"
		"3 Kissen auf deinem Kopf balancierst"
		"Push-ups machst"
		"Ein (echtes!) Baby im Arm hast"
		"Malst"
		"Dich auf dem Laufband verausgabst"
		"Dich im Wasser spiegelst"
		"Mit einer Gitarre posierst"
		"Sprossen isst"
		"Mit Lego spielst"
		"Eine Vinyl-Schallplatte in Händen hältst"
		"Einen Ballon aufpumpst"
		"Mit einer Gummiente sprichst"
		"In der Luft bist"
		"Mit neun anderen Menschen zusammen bist"
		"In einer Bücherei bist"
		"Auf einem Dach stehst"
		"Komplett in Weiß gekleidet bist"
		"Im Pyjama bist"
		"Zug fährst"
		"Die heutige Zeitung liest"
		"Skateboard fährst"
		"Gras im Mund hast"
		"In einem Klassenzimmer sitzt"
		"Eine (lebensgroße) Flagge schwenkst"
		"Einen Löffel aus der Nase hängen hast"
		"Eine Frisbee wirfst"
		"Mit einer Strumpfhose über dem Kopf rumläufst"
		"Unter einem Tisch herumhängst"
		"Einen Brief einwirfst"
		"In einem Kino bist"
		"Pfannkuchen bäckst"
		"Den Müll rausbringst"
		"In Vorhänge gewickelt bist"
		"Durch einen Strohhalm trinkst"
		"Eine Kerze anzündest"
		"Im Gras liegst"
		"Schreist"
		"Ohrenschützer trägst"
		"Dart spielst"
		"In einer Drehtür stehst"
		"Dich rasierst"
		"Dich in zwei Spiegeln unendlich reflektierst"
		"Einen Zauberwürfel hältst"
		"Ein Foto von dir hältst"
		"Auf einer Brücke bist"
		"Im Bett liegst"
		"Ein rosa T-Shirt trägst"
		"In einer Bar bist"
		"Sportkleidung trägst"
		"Ein Pferd streichelst"
		"Eine Brille trägst"
		"Dich im Kofferraum eines Autos befindest"
		"Klavier spielst"
		"Eine Fliege trägst"
		"Einen gefalteten Papierschwan in Händen hältst"
		"Eine Straßenlaterne erklimmst"
		"Eine Banane isst"
		"Einen Overall trägst"
		"Mit der Supermarkt-Kassiererin posierst"
		"Einen Kassetten-Walkman in der Hand hältst"
		"Superman-Fanartikel trägst"
		"Dein High-School-Diplom zeigst"
		"Mit einem dämpfenden Teekessel hantierst"
		"Schlittschuhe trägst"
		"Draußen Schneestiefel anhast"
		"Einen zusammengebauten Drachen hältst"
		"Eine Rechnung über $ 100 oder € 100 in der Hand hältst"
		"Ganz offensichtlich schwitzt"
		"Vor einem einfachen roten Hintergrund posierst"
		"Popcorn isst"
		"In tropfend nasser Kleidung bist"
		"Ein Bad nimmst"
		"Einen Helm auf dem Kopf hast"
		"Einem Straßenkünstler Geld gibst"
		"In einem Zelt bist"
		"Neben einer Ampel stehst"
		"In einer Hängematte liegst"
		"Deinen Mund zugeklebt hast"
		"Bei einem Gartenzwerg bist"
		"Spaghetti schlürfst"
		"Vor einem Museum stehst"
		"Bei einem Gemüsestand stehst"
		"Über einen Zaun kletterst"
		"Zu viel Lippenstift auf dem Mund hast"
		"Bei einer Bushaltestelle wartest"
		"In der Mitte eines Kreisverkehrs stehst"
		"Eine Perücke trägst"
		"Mit einer Statue posierst"
		"Eine Clownnase trägst"
		"Deine Klamotten mit der Innenseite nach außen trägst"
		"Zwei Uhren trägst"
		"Ein Playboy-Heft liest"
		"In einem McDonalds stehst"
		"Versuchst, die Nase mit der Zunge zu erreichen"
		"Das Ohr von einer anderen Person ableckst"
		"Die Stiefel von einer anderen Person küsst"
		"Ein volles Glas auf deinem Kopf balancierst"
		"Eine Bowlingkugel hältst"
		"Schwimmst"
		"Einen Anzug oder ein Abendkleid trägst"
		"Mit einer Strumpfpuppe sprichst"
		"In einer Mülltonne sitzt"
		"Auf der Toilette sitzt"
		"Mit einem Lampenschirm über dem Kopf posierst"
		"Harry Potter liest"
		"Einen Handstand machst"
		"Dich mit einem analogen Telefon zeigst"
		"Eine Hantel hebst"
		"Deinen Namen auf der Stirn trägst"
		"In der Autowaschanlage bist"
		"In Toilettenpapier gewickelt bist"
		"Mit Essstäbchen isst"
		"Einen eingelegten Hering isst"
		"Ein Hawaii-Hemd trägst"
		"Dich auf den Kopf stellst"
		"Versuchst, deinen großen Zeh zu beißen"
		"Dich durch ein Vergrößerungsglas siehst"
		"Mit jemandem zusammen bist, der auch ein Selfie macht"
		"Einen Besenstiel reitest"
		"Einen Hut aus Alufolie trägst"
		"Schielst"
		"Mit jemandem über 70 Jahre alt zusammen bist"
		"Holzschuhe trägst"
		"Einen Kinderwagen schiebst"
		"In einem Bus bist oder mit einem Taxifahrer zusammen"
		"Einen Poncho trägst"
		"Ein Insekt auf deiner Fingerspitze hast"
		"Ein Handtuch als Umhang trägst"
		"Eine Schlammmaske trägst"
		"Auf einem Handtuch in der Sonne liegst"
		"Planking ausprobierst"
		"Mit deiner Hand eine Tomate zerquetschst"
		"Eine CD/DVD auf deiner Nase balancierst"
		"Eine blau bemalte Zunge zeigst"
		"Eine Krawatte im Rambo-Stil trägst"
		"Eine Bibel liest"
		"Mit einem Henkelpokal posierst"
		"Einen Ball auf deinem Finger balancierst"
		"Staub saugst"
		"(Süßigkeiten)-Herzen über deinen Augen trägst"
		"Aus dem Schatten deiner Hände einen Hasen formst"
		"Eine Krone oder ein Diadem trägst"
		"Einen Barhocker leidenschaftlich umarmst"
		"Vor einem Filmplakat stehst"
		"Den Controller einer Spielkonsole in deinen Händen hältst"
		"Auf einem fatboy-Sitzsack hockst"
		"Auf einem Konzert bist"
		"Einen Cocktail trinkst"
		"Strickst"
		"Eine Kochmütze trägst"
		"Gegen einen Hund Seilziehen spielst"
		"Eine Duschhaube trägst"
		"Deine Haare föhnst"
		"Dich mit einem Schnurrbart aus Zahnpasta zeigst"
		"Mit einem Goldfisch posierst"
		"Ein Handtuch auf deinem Kopf trägst"
		"Eine Nadel einfädelst"
		"Hinter Gittern sitzt"
		"Dich mit einer Briefmarke auf der Stirn zeigst"
		"Neben einem Müllwagen stehst"
		"Auf einer Parkbank liegst"
		"Eine Schnecke hältst"
		"Deinen eigenen Namen googelst"
		"In einem Wäschegeschäft bist"
		"4 Haftnotizen auf deinem Gesicht trägst"
		"Deinen Bizeps beugst"
		"Dein Gesicht in Wasser tauchst"
		"Einen Badminton-Federball hältst"
		"5 Pullover trägst"
		"Pflanzen gießt"
		"Schuhe polierst"
		"Kleidung bügelst"
		"Einen Sombrero trägst"
		"Mit Stolz eine CD aus den 90ern in die Kamera zeigst"
		"5 Mobiltelefone gleichzeitig hältst"
		"Mit 2 anderen unter einem Regenschirm stehst"
		"Gemalte Augen auf deinen Augenlidern trägst"
		"Irokesenschnitt trägst"
		"Stifte aus deiner Nase hängen hast"
		"Wäscheklammern an den Ohren trägst"
		"Ein vierstöckiges Kartenhaus vor dir hast"
	]