exports.hunts = ->
	[
		"Brushing your teeth"
		"Riding a bike"
		"Kissing someone"
		"Wearing a cap"
		"And a police officer"
		"Drinking a glass of beer"
		"With a store mannequin"
		"Sitting on a swing"
		"Carrying someone"
		"With someone wearing the same shirt"
		"In an elevator"
		"Eating an ice cream"
		"Hugging a stuffed animal"
		"Wearing yellow sunglasses"
		"Wearing ski goggles"
		"Smoking a cigar"
		"And one of your parents"
		"With whipped cream on your face"
		"Blowing bubble gum"
		"Lying on the street"
		"Wearing a medal"
		"Petting an animal"
		"In a shopping cart"
		"Shampooing your hair"
		"Under a parking sign"
		"Wearing a flower in your hair"
		"On a slide"
		"Under an umbrella"
		"Hugging a tree"
		"In a church"
		"With a Ford Ka"
		"Balancing 3 pillows on your head"
		"Doing push-ups"
		"Holding a (real!) baby"
		"Painting"
		"On a treadmill"
		"Reflected in water"
		"With a guitar"
		"Eating sprouts"
		"Playing with lego"
		"Holding a vinyl record"
		"Inflating a balloon"
		"Talking to a rubber duck"
		"In mid-air"
		"With nine other people"
		"In a library"
		"Standing on a rooftop"
		"Dressed all white"
		"In pyjamas"
		"On a train"
		"With today's newspaper"
		"On a skateboard"
		"With grass in your mouth"
		"In a classroom"
		"Waving a (full-size) flag"
		"Hanging a spoon from your nose"
		"Throwing a frisbee"
		"With a panty hose over your head"
		"Hanging under a table"
		"Posting a letter"
		"In a cinema"
		"Baking pancakes"
		"Taking out the trash"
		"Wrapped in curtains"
		"Drinking through a straw"
		"Lighting a candle"
		"Lying in the grass"
		"Screaming"
		"Wearing earmuffs"
		"Playing darts"
		"In a revolving door"
		"Shaving"
		"Infinitely reflected in two mirrors"
		"Holding a Rubik's Cube"
		"Holding a photo of yourself"
		"On a bridge"
		"Lying in bed"
		"Wearing a pink shirt"
		"In a pub"
		"In sportswear"
		"Petting a horse"
		"Wearing glasses"
		"In the trunk of a car"
		"Playing the piano"
		"Wearing a bowtie"
		"Holding a folded paper swan"
		"Climbing a lamp post"
		"Eating a banana"
		"Wearing a onesie"
		"With the supermarket cashier"
		"Holding a cassette walkman"
		"Wearing Superman merchandise"
		"Showing your high school diploma"
		"With a steaming tea kettle"
		"Wearing ice skates"
		"Outside wearing snowboots"
		"Holding an assembled kite"
		"Holding a $100 or €100 bill"
		"Clearly sweating"
		"With just a plain red background"
		"Eating popcorn"
		"In drenching wet clothes"
		"Taking a bath"
		"Wearing a helmet"
		"Donating to a street performer"
		"In a tent"
		"With a traffic light"
		"Lying in a hammock"
		"With your mouth taped shut"
		"With a garden gnome"
		"Slurping spaghetti"
		"In front of a museum"
		"With a vegetable stand"
		"Climbing a fence"
		"Wearing too much lipstick"
		"At a busstop"
		"In the center of a roundabout"
		"Wearing a wig"
		"With a statue"
		"Wearing a clown nose"
		"Wearing your clothes inside out"
		"Wearing two watches"
		"Reading a Playboy magazine"
		"In a McDonald's"
		"Trying to tongue-touch your nose"
		"Licking someone's ear"
		"Kissing someone's boots"
		"Balancing a filled glass on your head"
		"Holding a bowling ball"
		"Swimming"
		"Wearing a suit or evening dress"
		"Talking to a sock puppet"
		"In a garbage bin"
		"Sitting on the toilet"
		"With a lampshade over your head"
		"Reading Harry Potter"
		"Doing a handstand"
		"With an analog phone"
		"Lifting a dumbbell"
		"With your name written on your forehead"
		"In a carwash"
		"Wrapped in toiletpaper"
		"Eating with chopsticks"
		"Eating a pickled herring"
		"Wearing a Hawaiian shirt"
		"Upside down"
		"Trying to bite your big toe"
		"Through a magnifying glass"
		"With someone else also taking a selfie"
		"Riding a broomstick"
		"Wearing a tinfoil hat"
		"Crossing your eyes"
		"With someone over 70 years old"
		"Wearing wooden shoes"
		"Walking a baby stroller"
		"With a bus/taxi driver"
		"Wearing a poncho"
		"With an insect on the tip of your finger"
		"Wearing a towel as a cape"
		"Wearing a mudmask"
		"Sunbathing on a towel"
		"Planking"
		"Squashing a tomato with your hand"
		"Balancing a CD/DVD on your nose"
		"Showing a blue tongue"
		"Wearing a tie rambo-style"
		"Reading a bible"
		"Showing off a trophy cup"
		"Balancing a ball on your finger"
		"Vacuuming"
		"With (candy) hearts in your eyes"
		"Making a shadowbunny with your hand(s)"
		"Wearing a crown or tiara"
		"Passionately hugging a bar stool"
		"In front of a movie poster"
		"Holding a game console controller"
		"On a fatboy sitting bag"
		"At a concert"
		"Drinking a cocktail"
		"Knitting"
		"Wearing a chef's hat"
		"Rope-pulling with a dog"
		"Wearing a showercap"
		"Blowdrying your hair"
		"With a moustache made from toothpaste" # new from here
		"With a goldfish"
		"Wearing a towel on your head"
		"Threading a needle"
		"Behind bars"
		"With a postage stamp on your forehead"
		"With a garbage truck"
		"Lying on a park bench"
		"Holding a snail"
		"Googling your own name"
		"In a lingerie store"
		"With 4 post-its on your face"
		"Flexing your biceps"
		"With your face submerged in water"
		"Holding a badminton shuttle"
		"Wearing 5 sweaters"
		"Watering plants"
		"Polishing shoes"
		"Ironing clothes"
		"Wearing a sombrero"
		"Proudly showing a CD from the 90s"
		"Holding 5 mobile phones"
		"Under an umbrella with 2 others"
		"With eyes drawn on your eyelids"
		"With mowhawk-style hair"
		"With pencils sticking out of your nose"
		"With clothes pegs on your ears"
		"With a 4-story house of cards"
		"with a globe"
        	"with a pen balanced on your forehead"
        	"while you're imitating a dog"
        	"with a cow"
        	"hanging through the window"
        	"in a cafe"
        	"in a frying"
        	"with one of your grandparents"
        	"in a closet"
        	"with 5 books on your head"
        	"with a person named Matthias"
        	"under your bed"
        	"while you eat an apple"
        	"with a pig"
        	"with 2 fingers in your nose"
        	"with a computer mouse"
        	"with 2 cats and / or dogs"
        	"A famous person"
        	"with pate"
        	"without pants"
        	"with a chewing gum stuck in your nose"
        	"with whipped cream on your belly"
	]
